clear all; close all;

addpath(genpath('Functions'));

ncdir = 'R:\Coorong-Local\Netcdf\';
savedir = 'Y:\Coorong Report\Process_Final/';

dirlist = dir([ncdir,'*.nc']);

vars = {...
    'WQ_DIAG_HAB_RUPPIA_HSI',...
    'WQ_DIAG_MAG_HSI',...
    'cell_A',...
    'H',...
    'V_x',...
    'V_y',...
    'D',...
    'SAL',...
    'TEMP',...
    'WQ_OXY_OXY',...
    'WQ_TRC_AGE',...
    'WQ_DIAG_PHY_TPHYS',...
    'WQ_DIAG_PHY_GPP',...
    'WQ_DIAG_MAG_GPP',...
    'WQ_DIAG_MAC_MAC'...
    'WQ_DIAG_MAC_GPP',...
    'WQ_DIAG_PHY_MPB',...
    'WQ_DIAG_PHY_BPP',...
    'WQ_DIAG_MAG_GPP_BEN',...
    'WQ_DIAG_MAG_MAG_BEN',...
    'WQ_DIAG_HAB_RUPPIA_HSI',...
    'WQ_DIAG_TOT_TN',...
    'WQ_DIAG_TOT_TOC',...
    'WQ_DIAG_TOT_TP',...
    'WQ_DIAG_TOT_TSS',...
    'WQ_DIAG_TOT_TURBIDITY',...
    'WQ_DIAG_HAB_RUPPIA_HSI_FLOWER',...
    'WQ_DIAG_HAB_RUPPIA_HSI_PLANT',...
    'WQ_DIAG_HAB_RUPPIA_HSI_SEED',...
    'WQ_DIAG_HAB_RUPPIA_HSI_SPROUT',...
    'WQ_DIAG_HAB_RUPPIA_HSI_TURION',...
    'WQ_DIAG_HAB_DRYTIME',...
    'WQ_DIAG_HAB_WETTIME',...
    'WQ_NIT_NIT',...
    'WQ_NIT_AMM',...
    'WQ_PHS_FRP',...
    'WQ_OGM_DOC',...
    'WQ_OGM_POC',...
    'WQ_OGM_DON',...
    'WQ_OGM_PON',...
    'WQ_OGM_DOP',...
    'WQ_OGM_POP',...
    'WQ_DIAG_TOT_TSS',...
    'WQ_DIAG_TOT_TURBIDITY',...
    };



%Vars = {...
%   'cell_A',...
%   'H',...
%   'V_x',...
%   'V_y',...
%   'D',...
%   'SAL',...
%   'TEMP',...
%   'WQ_TRC_AGE',...
%   'WQ_NCS_SS1',...
%   'WQ_NCS_SS2',...
%   'WQ_OXY_OXY',...
%   'WQ_SIL_RSI',...
%   'WQ_NIT_AMM',...
%   'WQ_NIT_NIT',...
%   'WQ_PHS_FRP',...
%   'WQ_PHS_FRP_ADS',...
%   'WQ_OGM_DOC',...
%   'WQ_OGM_POC',...
%   'WQ_OGM_DON',...
%   'WQ_OGM_PON',...
%   'WQ_OGM_DOP',...
%   'WQ_OGM_POP',...
%   'WQ_OGM_DOCR',...
%   'WQ_OGM_DONR',...
%   'WQ_OGM_DOPR',...
%   'WQ_OGM_CPOM',...
%   'WQ_PHY_GRN',...
%   'WQ_PHY_CRYPT',...
%   'WQ_PHY_DIATOM',...
%   'WQ_PHY_DINO',...
%   'WQ_PHY_BGA',...
%   'WQ_MAG_ULVA',...
%   'WQ_DIAG_MAC_MAC',...
%   'WQ_DIAG_PHY_BPP',...
%   'WQ_DIAG_PHY_TCHLA',...
%   'WQ_DIAG_MAG_TMALG',...
%   'WQ_DIAG_MAG_HSI',...
%   'WQ_DIAG_TOT_TN',...
%   'WQ_DIAG_TOT_TP',...
%   'WQ_DIAG_TOT_TOC',...
%   'WQ_DIAG_TOT_TSS',...
%   'WQ_DIAG_TOT_TURBIDITY',...
%   'WQ_DIAG_SDF_FSED_NIT',...
%   'WQ_DIAG_OGM_DENIT',...
%   'WQ_DIAG_NIT_DENIT',...
%   'WQ_DIAG_NIT_NITRIF',...
%   'WQ_DIAG_NIT_SED_NIT',...
%   'WQ_DIAG_OXY_SAT',...
%   'WQ_DIAG_PHY_TPHYS',...
%   };


%stop;


for bdb = length(dirlist)
    
    ncfile = [ncdir,dirlist(bdb).name];
    %ncfile = 'Z:\Busch\Studysites\Peel\2018_Modelling\Peel_WQ_Model_v5_2016_2017_3D_Murray\Output\sim_2016_2017_Open.nc';
    
    fdir = regexprep(dirlist(bdb).name,'.nc','');
    
    outdir = [savedir,regexprep(fdir,'\.','_'),'/'];
    %     if exist(outdir,'dir')
    %
    %     else
    
    %     the_vars = tfv_infonetcdf(ncfile);
    %     v_all = tfv_infonetcdf(ncfile);
    %     %vars = v_all(23:end);
    %     vars = v_all([20 21 23:end]);
    disp(ncfile);
    
    if ~exist(outdir,'dir')
        
        mkdir(outdir);
        %outdir = 'I:\Peel\Matfiles/Peel_WQ_Model_v5_2016_2017_3D_Murray/';
    end
    %load Export_Locations.mat;
    %shp = S;
    
    data = tfv_readnetcdf(ncfile,'names',{'idx2';'idx3';'cell_X';'cell_Y';'cell_A'});
    
    mdata = tfv_readnetcdf(ncfile,'time',1);
    Time = mdata.Time;
    %sites = {'Currency Creek';'Lake Albert WLR';'Lake Alex Middle'};
    
    %______________________________________________________________
    
    
    surf_ind = data.idx3;
    
    %         bottom_ind(1:length(data.idx3)-1) = data.idx3(2:end) - 1;
    %         bottom_ind(length(data.idx3)) = length(data.idx3);
    
    
    for i = 1:length(vars)
        disp(['Importing ',vars{i}]);
        
        mod = tfv_readnetcdf(ncfile,'names',vars(i));
        
        %
        
        
        savedata.X = data.cell_X;
        savedata.Y = data.cell_Y;
        savedata.Area = data.cell_A;
        savedata.Time = Time;
        %end
        
        switch vars{i}
            
            case 'H'
                savedata.(vars{i}) = mod.(vars{i});
            case 'D'
                savedata.(vars{i}) = mod.(vars{i});
            case 'cell_A'
                savedata.(vars{i}) = mod.(vars{i});
                %                     case  'WQ_DIAG_PHY_TCHLA'
                %                         savedata = run_tchla_cal(outdir);
            otherwise
                %savedata.(vars{i}).Top = mod.(vars{i})(surf_ind,:);
                savedata.(vars{i}).Bot = mod.(vars{i})(surf_ind,:);
                
        end
        
        
        
        save([outdir,vars{i},'.mat'],'savedata','-mat','-v7.3');
        clear savedata;
        % end
        
    end
    
end


