function savedata = run_tchla_cal(outdir)

% 'WQ_PHY_GRN',...
%     'WQ_PHY_CRYPT',...
%     'WQ_PHY_DIATOM',...
%     'WQ_PHY_DINO',...
%     'WQ_PHY_BGA',...
    
grn = load([outdir,'WQ_PHY_GRN.mat']);
cyp = load([outdir,'WQ_PHY_CRYPT.mat']);
dia = load([outdir,'WQ_PHY_DIATOM.mat']);
dino = load([outdir,'WQ_PHY_DINO.mat']);
bga = load([outdir,'WQ_PHY_BGA.mat']);

savedata.Time = grn.savedata.Time;
savedata.X = grn.savedata.X;
savedata.Y = grn.savedata.Y;
savedata.Area = grn.savedata.Area;


%          raw(mod).data.WQ_DIAG_PHY_TCHLA = (((tchl.WQ_PHY_GRN / 50)*12) + ...
%                         ((tchl.WQ_PHY_CRYPT / 50)*12) + ...
%                         ((tchl.WQ_PHY_DIATOM / 26)*12) + ...
%                         ((tchl.WQ_PHY_DINO / 40)*12) + ...
%                         ((tchl.WQ_PHY_BGA / 40)*12));


savedata.WQ_DIAG_PHY_TCHLA.Top = (((grn.savedata.WQ_PHY_GRN.Top / 50)*12) + ...
    ((cyp.savedata.WQ_PHY_CRYPT.Top / 50)*12) + ...
    ((dia.savedata.WQ_PHY_DIATOM.Top / 26)*12) + ...
    ((dino.savedata.WQ_PHY_DINO.Top / 40)*12) + ...
    ((bga.savedata.WQ_PHY_BGA.Top / 40)*12));

savedata.WQ_DIAG_PHY_TCHLA.Bot = (((grn.savedata.WQ_PHY_GRN.Bot / 50)*12) + ...
    ((cyp.savedata.WQ_PHY_CRYPT.Bot / 50)*12) + ...
    ((dia.savedata.WQ_PHY_DIATOM.Bot / 26)*12) + ...
    ((dino.savedata.WQ_PHY_DINO.Bot / 40)*12) + ...
    ((bga.savedata.WQ_PHY_BGA.Bot / 40)*12));