
clear; close all;

scenario = {...
    'Base',...
    'Scen1',...
    'Scen2',...
    };
    


fish = {...
    'mullowayHSI_del_2019',...
    'breamHSI_del_2019',...
    'gobyHSI_del_2019',...
    'flounderHSI_del_2019',...
    'mulletHSI_del_2019',...
    'congolliHSI_del_2019',...
    'hardyheadHSI_del_2019',...
    'mullowayHSI_del_2018',...
    'breamHSI_del_2018',...
    'gobyHSI_del_2018',...
    'flounderHSI_del_2018',...
    'mulletHSI_del_2018',...
    'congolliHSI_del_2018',...
    'hardyheadHSI_del_2018',...
    'mullowayHSI_del_2017',...
    'breamHSI_del_2017',...
    'gobyHSI_del_2017',...
    'flounderHSI_del_2017',...
    'mulletHSI_del_2017',...
    'congolliHSI_del_2017',...
    'hardyheadHSI_del_2017',...
};
%     'mullowayHSI_2019',...
%     'breamHSI_2019',...
%     'gobyHSI_2019',...
%     'flounderHSI_2019',...
%     'mulletHSI_2019',...
%     'congolliHSI_2019',...
%     'hardyheadHSI_2019',...
%     'mullowayHSI_2018',...
%     'breamHSI_2018',...
%     'gobyHSI_2018',...
%     'flounderHSI_2018',...
%     'mulletHSI_2018',...
%     'congolliHSI_2018',...
%     'hardyheadHSI_2018',...
%     'mullowayHSI_2017',...
%     'breamHSI_2017',...
%     'gobyHSI_2017',...
%     'flounderHSI_2017',...
%     'mulletHSI_2017',...
%     'congolliHSI_2017',...
%     'hardyheadHSI_2017',...
% };
  
fishnames = {...
    'mullowayHSI',...
    'breamHSI',...
    'gobyHSI',...
    'flounderHSI',...
    'mulletHSI',...
    'congolliHSI',...
    'hardyheadHSI',...
    'mullowayHSI',...
    'breamHSI',...
    'gobyHSI',...
    'flounderHSI',...
    'mulletHSI',...
    'congolliHSI',...
    'hardyheadHSI',...
    'mullowayHSI',...
    'breamHSI',...
    'gobyHSI',...
    'flounderHSI',...
    'mulletHSI',...
    'congolliHSI',...
    'hardyheadHSI',...
};
  
shp=shaperead('E:\Lowerlakes\GIS\ocean_north.shp');    %shapefile that contains the north ocean area of coorong




for n = 1:length(scenario)
    
    %load geo.mat;
    ncfile=['E:\Lowerlakes\Busch_Ruppia_modeloutput\MER_',scenario{n},'_20170701_20200701.nc'];
    dat = tfv_readnetcdf(ncfile,'timestep',1);
    cell_A=dat.cell_A; %cell area
    cellx=dat.cell_X;
    celly=dat.cell_Y;
    inpol=inpolygon(cellx,celly,shp(2).X,shp(2).Y);
    
for m = 1:length(fish)
    
    dataHSI=load(['E:\Lowerlakes\fishHSI\MER_Coorong_eWater_2020_v1\mat\',scenario{n}, '\',fish{m},'.mat']);

    disp(fish{m});
    
    outdir=['E:\Lowerlakes\fishHSI\MER_Coorong_eWater_2020_v1\mat\'];


    


     
     var=fieldnames(dataHSI);
     time=dataHSI.(var{1}).(['scen_',scenario{n}]).mdates;

    
    dv=datevec(time);
    dm=dv(:,2); %month
    dy=dv(:,1);  %year

    datearray=datenum(2017,7:42,1);
    vecarray=datevec(datearray); %split datetime into 6 columns

    

    vars={'HSI'};
    for kk=1:length(vars)
        data=dataHSI.(var{1}).(['scen_',scenario{n}]).(vars{kk});
        

        for vv=1:size(vecarray,1) %for all cells in the time frame
   
           inds=find(dy==vecarray(vv,1) & dm==vecarray(vv,2)); %find data in the same month of the same year
           
           %inds2=find(inds==1);
           
           if length(inds)>48
           disp(datestr(datearray(vv),'yyyymm'));
           cdata=mean(data(:,inds),2); %average HSI monthly in each cell
           tarea=0;
           
           for cc=1:size(cdata,1) %for all HSI
               if ~inpol(cc) %if it's not in polygon
               if cdata(cc)<0.3 
                   tarea=tarea+0; %if HSI<0.3, area deemed unsuitable
               elseif cdata(cc)>=0.3
                   tarea=tarea+cdata(cc).*cell_A(cc); %if HSI>=0.3, suitable area=HSI*area(m2)
               end
               end
           end
           
           montharea.(scenario{n}).(fishnames{m})(vv)=tarea/1e6; %convert area m2 to km2
           
           end
        end
    end
    
end

end

save([outdir,'\','monthlyarea_nonorth.mat'],'montharea','-mat','-v7.3')
