sites = {'cadell';...
        'caurnamont';...
        'currency_crk';...
        'langhorne_crk';...
        'mypolonga';...
        'narrung';...
        'swan_reach'};
for as = 1:length(sites)
    site  = sites{as};
    writeTFVMetcsvLL
end