clear all; close all;

addpath(genpath('tuflowfv'));

ncfile = 'I:\Lowerlakes\Coorong Only Simulations\Matt/lower_lakes.nc';

varname = {...
%    'WQ_TRC_SS1',...
% 'WQ_TRC_RET',...
% 'WQ_OXY_OXY',...
% 'WQ_SIL_RSI',...
% 'WQ_NIT_AMM',...
% 'WQ_NIT_NIT',...
% 'WQ_PHS_FRP',...
% 'WQ_PHS_FRP_ADS',...
% 'WQ_OGM_DOC',...
% 'WQ_OGM_POC',...
% 'WQ_OGM_DON',...
% 'WQ_OGM_PON',...
% 'WQ_OGM_DOP',...
% 'WQ_OGM_POP',...
% 'WQ_PHY_GRN',...
% 'WQ_MAG_ULVA',...
% 'WQ_MAG_ULVA_IN',...
% 'WQ_MAG_ULVA_IP',...
% 'WQ_DIAG_SDF_FSED_OXY',...
% 'WQ_DIAG_SDF_FSED_RSI',...
% 'WQ_DIAG_SDF_FSED_FRP',...
% 'WQ_DIAG_SDF_FSED_PON',...
% 'WQ_DIAG_SDF_FSED_DON',...
% 'WQ_DIAG_SDF_FSED_POP',...
% 'WQ_DIAG_SDF_FSED_DOP',...
% 'WQ_DIAG_SDF_FSED_POC',...
% 'WQ_DIAG_SDF_FSED_DOC',...
% 'WQ_DIAG_SDF_FSED_DIC',...
% 'WQ_DIAG_MAC_PAR',...
% 'WQ_DIAG_MAC_GPP',...
% 'WQ_DIAG_MAC_P_R',...
% 'WQ_DIAG_MAC_MAC',...
% 'WQ_DIAG_MAC_LAI',...
% 'WQ_DIAG_MAC_MAC_AG',...
% 'WQ_DIAG_MAC_MAC_BG',...
% 'WQ_DIAG_TRC_SS1_VVEL',...
% 'WQ_DIAG_TRC_TAU_0',...
% 'WQ_DIAG_TRC_EPSILON',...
% 'WQ_DIAG_TRC_FS1',...
% 'WQ_DIAG_TRC_D_TAUB',...
% 'WQ_DIAG_TRC_RESUS',...
% 'WQ_DIAG_OXY_SED_OXY',...
% 'WQ_DIAG_OXY_ATM_OXY_FLUX',...
% 'WQ_DIAG_OXY_SAT',...
% 'WQ_DIAG_SIL_SED_RSI',...
% 'WQ_DIAG_NIT_NITRIF',...
% 'WQ_DIAG_NIT_DENIT',...
% 'WQ_DIAG_NIT_ANAMMOX',...
% 'WQ_DIAG_NIT_DNRA',...
% 'WQ_DIAG_NIT_SED_AMM',...
% 'WQ_DIAG_NIT_SED_NIT',...
% 'WQ_DIAG_PHS_SED_FRP',...
% 'WQ_DIAG_OGM_PSED_POC',...
% 'WQ_DIAG_OGM_PSED_PON',...
% 'WQ_DIAG_OGM_PSED_POP',...
% 'WQ_DIAG_OGM_CDOM',...
% 'WQ_DIAG_PHY_GRN_NTOP',...
% 'WQ_DIAG_PHY_GRN_FI',...
% 'WQ_DIAG_PHY_GRN_FNIT',...
% 'WQ_DIAG_PHY_GRN_FPHO',...
% 'WQ_DIAG_PHY_GRN_FSIL',...
% 'WQ_DIAG_PHY_GRN_FT',...
% 'WQ_DIAG_PHY_GRN_FSAL',...
% 'WQ_DIAG_PHY_PSED_PHY',...
% 'WQ_DIAG_PHY_GPP',...
% 'WQ_DIAG_PHY_NCP',...
% 'WQ_DIAG_PHY_PPR',...
% 'WQ_DIAG_PHY_NPR',...
% 'WQ_DIAG_PHY_NUP',...
% 'WQ_DIAG_PHY_PUP',...
% 'WQ_DIAG_PHY_CUP',...
% 'WQ_DIAG_PHY_PAR',...
% 'WQ_DIAG_PHY_TCHLA',...
% 'WQ_DIAG_PHY_TPHYS',...
% 'WQ_DIAG_PHY_IN',...
% 'WQ_DIAG_PHY_IP',...
% 'WQ_DIAG_PHY_MPB',...
% 'WQ_DIAG_PHY_BPP',...
% 'WQ_DIAG_PHY_MPBV',...
% 'WQ_DIAG_MAG_ULVA_NTOP',...
% 'WQ_DIAG_MAG_ULVA_FI',...
% 'WQ_DIAG_MAG_ULVA_FNIT',...
% 'WQ_DIAG_MAG_ULVA_FPHO',...
% 'WQ_DIAG_MAG_ULVA_FSIL',...
% 'WQ_DIAG_MAG_ULVA_FT',...
% 'WQ_DIAG_MAG_ULVA_FSAL',...
% 'WQ_DIAG_MAG_ULVA_FI_BEN',...
% 'WQ_DIAG_MAG_ULVA_FNIT_BEN',...
% 'WQ_DIAG_MAG_ULVA_FPHO_BEN',...
% 'WQ_DIAG_MAG_ULVA_FT_BEN',...
% 'WQ_DIAG_MAG_ULVA_FSAL_BEN',...
% 'WQ_DIAG_MAG_GPP',...
% 'WQ_DIAG_MAG_NCP',...
% 'WQ_DIAG_MAG_PPR',...
% 'WQ_DIAG_MAG_NPR',...
% 'WQ_DIAG_MAG_NUP',...
% 'WQ_DIAG_MAG_PUP',...
% 'WQ_DIAG_MAG_CUP',...
% 'WQ_DIAG_MAG_PAR',...
% 'WQ_DIAG_MAG_TCHLA',...
'WQ_DIAG_MAG_IN',...
'WQ_DIAG_MAG_IP',...
'WQ_DIAG_HAB_RUPPIA_HSI',...
'WQ_DIAG_HAB_RUPPIA_HSI_PLANT',...
'WQ_DIAG_HAB_RUPPIA_HSI_FLOWER',...
'WQ_DIAG_HAB_RUPPIA_HSI_SEED',...
'WQ_DIAG_HAB_RUPPIA_HSI_TURION',...
'WQ_DIAG_HAB_RUPPIA_HSI_SPROUT',...
};

outfile = 'limits1.txt';

fid = fopen(outfile,'wt');

fid2 = fopen('Limits_3.txt','wt');


fprintf(fid,'varname = {...\n');

for i = 1:length(varname)
    pstring = ['''',varname{i},'''',',...'];
    fprintf(fid,'%s\n',pstring);
end

fprintf(fid,'};\n');
fprintf(fid,'\n');
for i = 1:length(varname)
    
    disp(varname{i});
    
    data = tfv_readnetcdf(ncfile,'names',varname(i));
    
    clear function
    
    min_val = min(min(data.(varname{i})));
    max_val = max(max(data.(varname{i})));
    mean_val =mean(data.(varname{i})(:));
    
    if min_val == max_val
        max_val = max_val + 1;
    end
    
    pstring = ['def.cAxis(',num2str(i),').value = [',num2str(min_val),' ',num2str(max_val),'];'];
    
    %fprintf(fid,'%s,%s,%10.6f\n',varname{i},pstring,mean_val);
    fprintf(fid,'%s\n',pstring);
    
    pstring2 = [varname{i},',',num2str(min_val),',',num2str(max_val)];

    
    fprintf(fid2,'%s\n',pstring2);
    
    clear pstring pstring2;
    
end

fclose(fid);
fclose(fid2);