function merge_area_data_into_regions

addpath(genpath('tuflowfv'));


int(1).scenarios = {...
    '013_Weir_2_SC40_Parnka_Fixed_TS',...
    '013_Weir_11_Parnka_SC40_SAL',...
    '013_Weir_12_noWeir_SC40_SAL_PGrid',...
    };

int(1).labels = {...
    'Parnka_SC40',...
    'Parnka_SC40_Salinity',...
    'No_Weir_SC40_Salinity',...
    };

int(1).leg = {...
    'Parnka SC40',...
    'Parnka SC40 High Salinity',...
    'No Weir SC40 High Salinity',...
    };

int(1).outfile = 'High_Salinity_IC.mat';

%____________________________________________

int(2).scenarios = {...
    '012_ORH_2014_2016_1',...
    '013_Weir_7_SC55_Needles',...
    '013_Weir_8_SC55_Parnka',...
    '013_Weir_9_SC55_noWeir',...
    };

int(2).labels = {...
    'ORH',...
    'Needles_SC55',...
    'Parnka_SC55',...
    'No_Weir_SC55',...
    };

int(2).leg = {...
    'ORH',...
    'Needles SC55',...
    'Parnka SC55',...
    'No Weir SC55',...
    };

int(2).outfile = 'SC55_Comparison.mat';

%____________________________________________

int(3).scenarios = {...
    '012_Weir_3_SC40_noWeir',...
    '013_Weir_9_SC55_noWeir',...
    '012_Weir_6_SC70_noWeir',...
    '013_Weir_2_SC40_Parnka_Fixed_TS',...
    '013_Weir_8_SC55_Parnka',...
    '013_Weir_5_SC70_Parnka',...
    };

int(3).labels = {...
    'No_Weir_40',...
    'No_Weir_55',...
    'No_Weir_70',...
    'Parnka_40',...
    'Parnka_55',...
    'Parnka_70',...
    };

int(3).leg = {...
    'No Weir SC40',...
    'No Weir SC55',...
    'No Weir SC70',...
    'Parnka SC40',...
    'Parnka SC55',...
    'Parnka SC70',...
    };

int(3).outfile = 'Salt_Creek_Flows.mat';


%____________________________________________

int(4).scenarios = {...
    '013_Weir_4_SC70_Needles',...
    '013_Weir_10_SC70_Needles_Sill04',...
    '013_ORH_2014_2016_Needles_Sill',...
    '012_Weir_6_SC70_noWeir',...
     '012_ORH_2014_2016_1',...
    };

int(4).labels = {...
    'Needles_SC70',...
    'Needles_SC70_Sill',...
    'ORH_Sill',....
    'NO_Weir',...
     'ORH',...
    };

int(4).leg = {...
    'Needles SC70 \newline(Sill 0.6m)',...
    'Needles SC70 \newline(Sill 0.4m)',...
    'Needles ORH \newline(Sill 0.4m)',...
    'No Weir SC70',...
     'ORH',...
    };

int(4).outfile = 'Sill_Comparison.mat';
%____________________________________________

int(5).scenarios = {...
    '013_Weir_2_SC40_Parnka_Fixed_TS',...
    '013_Weir_2_SC40_Parnka',...
        '013_Weir_13_Parnka_SC55_J',...
    '012_Weir_3_SC40_noWeir',...
    };

int(5).labels = {...
    'Parnka_SC40',...
    'Parnka_SC40_Aug',...
        'PArnka_SC40_J',...
    'No_Weir_SC40',...
    };

int(5).leg = {...
    'Parnka SC40 (Sept.)',...
    'Parnka SC40 (Aug.)',...
        'Parnka SC40 (July)',...
    'No Weir SC40',...
    };

int(5).outfile = 'Timing_Comparison.mat';



int(6).scenarios = {...
    '012_ORH_2014_2016_1',...
    '013_Weir_1_SC40_Needles',...
    '013_Weir_2_SC40_Parnka_Fixed_TS',...
    '012_Weir_3_SC40_noWeir',...
    '013_Weir_4_SC70_Needles',...
    '013_Weir_5_SC70_Parnka',...
    '012_Weir_6_SC70_noWeir',...
    '013_Weir_7_SC55_Needles',...
    '013_Weir_8_SC55_Parnka',...
    '013_Weir_9_SC55_noWeir',...
    '013_Weir_10_SC70_Needles_Sill04',...
    '013_Weir_11_Parnka_SC40_SAL',...
    '013_Weir_12_noWeir_SC40_SAL_PGrid',...
    '013_Weir_2_SC40_Parnka',...
    '013_Weir_13_Parnka_SC55_J',...
    '012_Weir_3_SC40_noWeir',...
    };

int(6).labels = {...
    'ORH',...
    'Needles_SC40',...
    'Parnka_SC40',...
    'NoWeir_SC40',...
    'Needles_SC70',...
    'Parnka_SC70',...
    'NoWeir_SC70',...
    'Needles_SC55',...
    'Parnka_SC55',...
    'NoWeir_SC55',...
    'Needles_SC70_Sill04',...
    'Parnka_SC40_High_Salinity',...
    'NoWeir_SC40_High_Salinity',...
    'Parnka_SC40_Aug',...
            '013_Weir_13_Parnka_SC55_J',...
    '012_Weir_3_SC40_noWeir',...
    };

int(6).leg = {...
    'ORH',...
    'Needles SC40',...
    'Parnka SC40',...
    'No Weir SC40',...
    'Needles SC70',...
    'Parnka SC70',...
    'No Weir SC70',...
    'Needles SC55',...
    'Parnka SC55',...
    'No Weir SC55',...
    'Needles SC70 (Sill 0.4m)',...
    'Parnka SC40 High Salinity',...
    'No Weir SC40 High Salinity',...
    'Parnka SC40 (Aug.)',...
    '013_Weir_13_Parnka_SC55_J',...
    '012_Weir_3_SC40_noWeir',...
    };

int(6).outfile = 'All.mat';
















basedir = 'D:\Cloud\Dropbox\Data_Lowerlakes\Illustrator Processing\';


for bb = 1:length(int)
    
    outfile = int(bb).outfile;
    
    for i = 1:length(int(bb).scenarios)
        int(bb).scenarios{i}
        
        ncfile = ['I:\Lowerlakes\Coorong Weir Simulations\',int(bb).scenarios{i},'/Output/coorong.nc'];
        
        dat = tfv_readnetcdf(ncfile,'timestep',1);
        
        cell_X = dat.cell_X;
        cell_Y = dat.cell_Y;
        cell_A = dat.cell_A;
        
        
        dirlist = dir([basedir,int(bb).scenarios{i},'/Sheets/']);
        
        for j = 3:length(dirlist)
            
            dirname = [basedir,int(bb).scenarios{i},'/Sheets/',dirlist(j).name,'/'];
            
            year = str2num(dirlist(j).name);
            
            
            load([dirname,'1_adult_new/HSI_adult.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Adult = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'2_flower_new/HSI_flower.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Flower = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'3_seed_new/HSI_seed.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Seed = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'4_turion_new/HSI_turion.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Turion = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'5_sprout_new/HSI_sprout.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Sprout = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'HSI_asexual.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Asexual = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
            load([dirname,'HSI_sexual.mat']);
            data.(int(bb).labels{i}).(['s',dirlist(j).name]).Sexual = ...
                classify_region_data(min_cdata,cell_X,cell_Y,cell_A);
            
        end
        
        
        
        data.(int(bb).labels{i}).leg = int(bb).leg{i};
    end
    
    save([basedir,outfile],'data','-mat');
    
    clear data;
end
end

function data = classify_region_data(cdata,X,Y,A)

shp = shaperead('GIS/Final_Ruppia_Area.shp');

for i = 1:length(shp)
    
    inpol = inpolygon(X,Y,shp(i).X,shp(i).Y);
    
    region_name = regexprep(shp(i).Name,' ','_');
    
    sss = find(inpol == 1);
    
    data.(region_name) = sum(cdata(sss) .* A(sss));
    
    data.Total = sum(cdata .* A);
    
end
end


